# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Elizaveta Vereshchagina
tagline:          'Research Scientist'
description:      'Research Scientist'
company:          Sintef
company_url:      'https://www.sintef.no/en/'
e-mail:           'Elizaveta.Vereshchagina@sintef.no'
url:              https://evereshchagina.github.io
baseurl:          /

# Social networks
facebook:         'https://www.facebook.com/elizaveta.vereshchagina'
twitter:          'https://twitter.com/evereshchagina'
linkedin:         'https://www.linkedin.com/in/evereshchagina'
researchgate:     'https://www.researchgate.net/profile/Elizaveta_Vereshchagina'

# Google Maps API
maps:
    google:
      api_key:    AIzaSyCVrIEhIXdAHyZEJq3irCA5U98GhrCEZDs

# Author
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate, jemoji, jekyll-maps]


github:
  repo:           https://github.com/evereshchagina
